### ISSUE TITLE
README 里写的 `QzoneLogin` 方法找不到

### ISSUE THREAD

**Issue by RockChinQ** [HHU-47133/qzone#15]
我看 README 写了一个 QzoneLogin 的示例，但 examples 里的测试流程是一步一步执行，而全局搜索也没有这个方法，

![image](https://github.com/user-attachments/assets/fc680995-6737-41a5-92df-4b5fd75cfbd9)

请问推荐的登录方式是？

**Comment by intchensc** [comment]
sorry 忘记更新README，为了方便在web中使用，登录方式做了修改
https://github.com/HHU-47133/qzone/blob/b0b1c0b049dfd46de23571fa583176da4ac13b0e/examples/a_login_test.go#L25-L38
分为”二维码获取“、”二维码状态验证"两阶段，"test-uid"用于绑定web用户

**Comment by RockChinQ** [comment]
好的，谢谢。
