### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by limu520** [HHU-47133/qzone#7]
可以添加一个账号密码的登录功能嘛，发现二维码扫描获取的sk没有办法保证存活，一直访问保持存活的方案会在凌晨的2.30统一刷新下线

**Comment by intchensc** [comment]
扫码登录cookie有效期为48h，账号密码登录会有人机验证，建议你通过开源QQ机器人框架持续获取并更新cookie
[NapCatQQ](https://github.com/NapNeko/NapCatQQ)

**Comment by intchensc** [comment]
> 可以添加一个账号密码的登录功能嘛，发现二维码扫描获取的sk没有办法保证存活，一直访问保持存活的方案会在凌晨的2.30统一刷新下线
扫码登录cookie有效期为48h，账号密码登录会有人机验证，建议你通过开源QQ机器人框架持续获取并更新cookie
[NapCatQQ](https://github.com/NapNeko/NapCatQQ)

**Comment by intchensc** [comment]
> 可以添加一个账号密码的登录功能嘛，发现二维码扫描获取的sk没有办法保证存活，一直访问保持存活的方案会在凌晨的2.30统一刷新下线

扫码登录cookie有效期为48h，账号密码登录会有人机验证，建议你通过开源QQ机器人框架持续获取并更新cookie
[NapCatQQ](https://github.com/NapNeko/NapCatQQ)
